import { useMemo, useState, type ReactNode } from 'react';
import {
  Activity, AlertTriangle, BarChart3, BookOpen, Building2, CheckCircle2,
  ChevronDown, CircleHelp, Clock3, Code2, Database, Filter, Gauge, Info, Landmark,
  Layers3, LayoutDashboard, Plane, ReceiptIndianRupee, RefreshCw,
  Route as RouteIcon, Search, ShieldCheck, Sigma, SlidersHorizontal, UserCog, X,
  type LucideIcon,
} from 'lucide-react';
import type { UserRole } from '../constants/auth';
import { useAuth } from '../context/AuthContext';

type SectionId = 'etl' | 'methodology' | 'scraping' | 'dashboard' | 'roles' | 'glossary' | 'faqs';
type GlossaryCategory = 'Index & methodology' | 'Institutions' | 'Fares & booking' | 'Data & quality';

interface GuideSection {
  id: SectionId; letter: string; title: string; shortTitle: string;
  description: string; searchText: string; icon: LucideIcon;
}

interface GlossaryEntry {
  term: string; short?: string; category: GlossaryCategory; meaning: string; importance: string;
}

const GUIDE_SECTIONS: readonly GuideSection[] = [
  { id: 'etl', letter: 'A', title: 'ETL Pipeline', shortTitle: 'ETL Pipeline', description: 'How fares are extracted, cleaned and stored.', searchText: 'extract transform load airline ota booking window metadata duplicate missing sold out outlier fare tax udf convenience standard route sqlalchemy sqlite repository', icon: Layers3 },
  { id: 'methodology', letter: 'B', title: 'APIX Methodology', shortTitle: 'APIX Methodology', description: 'Formula, route weights, base period and calculation frequency.', searchText: 'apix index formula weighted price relative route weight base period current airfare city pair daily weekly monthly example', icon: Sigma },
  { id: 'scraping', letter: 'C', title: 'How Scraping Works', shortTitle: 'Scraping', description: 'Collection technology, controls and source coverage.', searchText: 'python serpapi google flights api rate limit retry domestic routes fare intelligence', icon: Code2 },
  { id: 'dashboard', letter: 'D', title: 'Dashboard Walkthrough', shortTitle: 'Dashboard', description: 'How to read every major visual and filter.', searchText: 'dashboard widget apix trend chart axes hover route heatmap colour hotspot filter airline comparison lead time elasticity date route booking window', icon: LayoutDashboard },
  { id: 'roles', letter: 'E', title: 'Role-Based Guide', shortTitle: 'Your Role Guide', description: 'Tasks for NSO, RBI and MoSPI/DGCA users.', searchText: 'nso cpi report download route basket rbi inflation volatility lead time ai observation mospi dgca admin user management scraper data quality', icon: UserCog },
  { id: 'glossary', letter: 'F', title: 'Business Glossary', shortTitle: 'Glossary', description: 'Plain-language definitions of important terms.', searchText: 'business glossary cpi apix nso mospi rbi dgca ota representative basket base fare tax udf convenience elasticity outlier repository etl volatility', icon: BookOpen },
  { id: 'faqs', letter: 'G', title: 'Frequently Asked Questions', shortTitle: 'FAQs', description: 'Concise answers to common operational questions.', searchText: 'faq why routes windows dgca fare scrape fail duplicate sold out sqlite export refresh source quality login permission revise weight missing data', icon: CircleHelp },
];

const GLOSSARY: readonly GlossaryEntry[] = [
  { term: 'Consumer Price Index', short: 'CPI', category: 'Index & methodology', meaning: 'A measure of how the prices paid by households change over time. Air travel is included because passenger fares form part of household spending on transport services.', importance: 'VAYUSETU supplies timely airfare evidence that can support the air-transport component of CPI measurement.' },
  { term: 'Airfare Price Index', short: 'APIX', category: 'Index & methodology', meaning: 'VAYUSETU’s fixed-base modified Laspeyres index of domestic passenger airfare change. It combines matched fare relatives using base expenditure shares.', importance: 'It turns thousands of fare observations into one consistent signal for tracking airfare inflation over time.' },
  { term: 'National Statistical Office', short: 'NSO', category: 'Institutions', meaning: 'The statistical office within MoSPI responsible for compiling and publishing major official statistics, including India’s Consumer Price Index.', importance: 'NSO officials can use APIX trends, route evidence and reports when monitoring the airfare component of consumer inflation.' },
  { term: 'Ministry of Statistics and Programme Implementation', short: 'MoSPI', category: 'Institutions', meaning: 'The Government of India ministry that sets statistical standards and oversees the production of official statistics through the NSO.', importance: 'MoSPI provides institutional oversight for inflation measurement and administers VAYUSETU’s routes, users and data operations.' },
  { term: 'Reserve Bank of India', short: 'RBI', category: 'Institutions', meaning: 'India’s central bank. It studies inflation and its drivers when making monetary-policy assessments and communicating risks to price stability.', importance: 'APIX gives RBI analysts a focused, high-frequency view of airfare inflation, volatility and booking-time behaviour.' },
  { term: 'Directorate General of Civil Aviation', short: 'DGCA', category: 'Institutions', meaning: 'India’s civil aviation regulator and a source of official domestic passenger-traffic information by route and airline.', importance: 'VAYUSETU uses DGCA traffic shares to select representative routes and give busier routes proportionately greater weight.' },
  { term: 'Online Travel Aggregator', short: 'OTA', category: 'Fares & booking', meaning: 'A digital booking platform - such as MakeMyTrip, Goibibo or Ixigo - that displays and sells flights from multiple airlines in one place.', importance: 'OTA observations help VAYUSETU compare the fares and fees that passengers encounter across different booking channels.' },
  { term: 'Representative Route Basket', category: 'Index & methodology', meaning: 'A selected set of important domestic city pairs used to measure airfare movement. It represents the market without collecting every route in India.', importance: 'A stable basket makes collection practical and allows like-for-like comparison across dates while retaining broad passenger coverage.' },
  { term: 'Route Weight', category: 'Index & methodology', meaning: 'The base expenditure share assigned to a city pair in APIX, calculated from DGCA passenger share multiplied by its base-period representative fare.', importance: 'Weights reflect both how heavily a route is travelled and its base price level.' },
  { term: 'Base Period', category: 'Index & methodology', meaning: 'The reference period against which later price levels are compared, usually assigned an index value of 100.', importance: 'A fixed base gives every APIX value a common benchmark, so officials can interpret the size and direction of fare change.' },
  { term: 'Base Fare', category: 'Fares & booking', meaning: 'The airline’s ticket price before government taxes, airport charges and booking-platform fees are added.', importance: 'Separating the base fare helps VAYUSETU distinguish airline pricing decisions from taxes and third-party charges.' },
  { term: 'Taxes & User Development Fee', short: 'Taxes & UDF', category: 'Fares & booking', meaning: 'Mandatory taxes and airport-related charges added to a ticket. UDF is collected at specified airports to support airport development and operations.', importance: 'Recording these separately explains the difference between the base fare and the final amount shown to a passenger.' },
  { term: 'Convenience Fee', category: 'Fares & booking', meaning: 'A service or transaction charge added by an airline website or OTA for processing a booking, often near checkout.', importance: 'Capturing it separately makes total-fare comparisons fair across platforms and prevents it being mistaken for airline fare inflation.' },
  { term: 'Booking Window', short: 'T+1 to T+60', category: 'Fares & booking', meaning: 'The number of days between fare collection and departure: T+1 is tomorrow, while T+7, T+15, T+30 and T+60 are 7, 15, 30 and 60 days ahead.', importance: 'Fixed windows let officials compare like with like and see how prices behave as the departure date approaches.' },
  { term: 'Lead-Time Elasticity', category: 'Index & methodology', meaning: 'The way airfare changes as the time remaining before departure becomes shorter or longer. It shows how sensitive fares are to the booking window.', importance: 'It helps users identify early-booking savings, sharp last-minute increases and routes with unusual pricing behaviour.' },
  { term: 'Fare Observation', category: 'Data & quality', meaning: 'One time-stamped price record for a specific route, airline, travel date, flight and booking channel.', importance: 'Fare observations are the basic evidence used to calculate route-level movements and the overall APIX.' },
  { term: 'Outlier', category: 'Data & quality', meaning: 'An abnormally high or low fare that differs greatly from comparable observations, possibly because of an error or exceptional market condition.', importance: 'VAYUSETU flags and reviews outliers so isolated values do not distort averages or APIX; valid unusual fares can still be retained.' },
  { term: 'Duplicate Fare', category: 'Data & quality', meaning: 'The same flight and price captured more than once for the same collection time and booking conditions.', importance: 'Removing duplicates prevents one observation from receiving extra influence in route averages and index calculation.' },
  { term: 'Price Insights', category: 'Data & quality', meaning: 'Google Flights fare context containing the lowest observed price, typical price range and a Low, Typical or High classification when available.', importance: 'It gives analysts market context without estimating unavailable fare-breakup or seat-inventory values.' },
  { term: 'Historical Airfare Repository', category: 'Data & quality', meaning: 'A time-stamped database of cleaned fare observations collected from airline and OTA websites over successive scraping runs.', importance: 'It supports trend analysis, base-period comparison, auditing, anomaly checks and repeatable APIX calculations.' },
  { term: 'Extract, Transform, Load', short: 'ETL', category: 'Data & quality', meaning: 'The workflow that collects raw fares, cleans and standardises them, and stores the approved records in the database.', importance: 'ETL provides a consistent path from website data to trustworthy dashboard indicators and downloadable reports.' },
  { term: 'Route Volatility', category: 'Index & methodology', meaning: 'The degree to which fares on a city pair move up and down over time. Higher volatility means prices are changing more sharply or frequently.', importance: 'It helps analysts separate steady inflation from short-lived spikes and identify corridors that need closer review.' },
];

const FAQS = [
  ['Why does VAYUSETU use representative routes?', 'Collecting every route would add cost and unstable coverage. A passenger-weighted basket captures the most important market movements while remaining consistent over time.'],
  ['Why use T+1, T+7, T+15, T+30 and T+60?', 'These windows capture last-minute, short, medium and advance booking behaviour. Fixed windows also make observations comparable between dates and routes.'],
  ['How is APIX different from DGCA average fares?', 'A simple average reports a level. APIX measures fixed-base price change and combines geometric matched-cohort relatives using route base-expenditure weights.'],
  ['What happens if a scraping run fails?', 'The run is logged, retried within configured limits and flagged for review. Previously validated records remain available; failed collection is never silently replaced with zero.'],
  ['How are duplicate fares removed?', 'Records with the same source, flight, route, travel date, booking window and collection context are matched. Only the valid canonical observation is retained.'],
  ['What happens when price insights are unavailable?', 'The unavailable insight fields remain null while the displayed total fare can still be stored. Missing insights do not cause the scrape to fail.'],
  ['Why does the prototype use SQLite?', 'SQLite is portable, auditable and simple to deploy for a prototype. The data layer can move to a managed production database as collection volume grows.'],
  ['How often is APIX updated?', 'It can be produced daily from validated observations, then aggregated into weekly and monthly series for reporting and comparison.'],
  ['Does APIX measure the cheapest advertised fare?', 'No. It uses comparable, validated fare observations under defined route and booking-window rules rather than one promotional headline price.'],
  ['Are taxes and fees included?', 'VAYUSETU captures the components separately. A configured index series can use a consistent payable-fare definition while still allowing analysts to inspect base fare and fees.'],
  ['How are missing values treated?', 'Required missing fields are rejected or quarantined. Optional fields may be standardised only under documented rules; values are not invented to make a record appear complete.'],
  ['How are unusual fares checked?', 'Statistical rules flag extreme values against comparable route and window observations. A flag prompts review - it does not automatically prove the fare is wrong.'],
  ['Where do route weights come from?', 'They are derived from official DGCA passenger traffic shares for the representative city-pair basket and are normalised to total 100%.'],
  ['Can route weights be changed?', 'Authorised MoSPI/DGCA administrators can maintain the basket. Changes should be documented, validated and applied from a stated effective date.'],
  ['Why can observed prices change?', 'Availability, search timing and airline pricing can change. Source, timestamp, total fare and available Google price insights are retained for analysis.'],
  ['What does APIX above 100 mean?', 'It means weighted airfares are higher than in the base period. For example, 104.5 means the measured basket is 4.5% above its base-period level.'],
  ['Can dashboard data be downloaded?', 'Users with download permission can export the available report or dataset for authorised analysis, subject to the labels and coverage notes shown.'],
  ['Who can manage users?', 'Only the MoSPI administrator role has access to user-management controls in the current role model.'],
  ['Are AI-generated observations official statistics?', 'No. They are supporting analytical prompts and must be reviewed alongside validated data and official statistical procedures before use.'],
  ['How should a data-quality alert be used?', 'Open the affected source, route or period, review its validation details and document the resolution. Do not infer a market change from an unresolved technical alert.'],
] as const;

const CATEGORY_META: Record<GlossaryCategory, { icon: LucideIcon; tone: string }> = {
  'Index & methodology': { icon: SlidersHorizontal, tone: 'bg-blue-50 text-[#1769AA] ring-blue-100' },
  Institutions: { icon: Landmark, tone: 'bg-violet-50 text-violet-700 ring-violet-100' },
  'Fares & booking': { icon: ReceiptIndianRupee, tone: 'bg-amber-50 text-amber-700 ring-amber-100' },
  'Data & quality': { icon: Database, tone: 'bg-teal-50 text-[#0F8B8D] ring-teal-100' },
};

function Callout({ children, tone = 'info' }: { children: ReactNode; tone?: 'info' | 'technical' | 'warning' }) {
  const styles = tone === 'warning' ? 'border-amber-200 bg-amber-50 text-amber-950' : tone === 'technical' ? 'border-violet-200 bg-violet-50 text-violet-950' : 'border-blue-200 bg-blue-50 text-blue-950';
  const Icon = tone === 'warning' ? AlertTriangle : tone === 'technical' ? Code2 : Info;
  return <div className={`flex gap-3 rounded-xl border p-4 text-xs leading-5 ${styles}`}><Icon className="mt-0.5 h-4 w-4 shrink-0" /><div>{children}</div></div>;
}

function MiniCard({ icon: Icon, title, children }: { icon: LucideIcon; title: string; children: ReactNode }) {
  return <div className="rounded-2xl border border-[#E2E8F0] bg-white p-5"><div className="mb-3 flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-[#1769AA]"><Icon className="h-4 w-4" /></div><h3 className="font-heading text-sm font-extrabold text-[#172033]">{title}</h3><div className="mt-2 text-xs leading-5 text-[#64748B]">{children}</div></div>;
}

function BulletList({ items }: { items: readonly string[] }) {
  return <ul className="space-y-2">{items.map((item) => <li key={item} className="flex gap-2"><CheckCircle2 className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#0F8B8D]" /><span>{item}</span></li>)}</ul>;
}

function EtlContent() {
  return <div className="space-y-5">
    <div className="grid gap-4 lg:grid-cols-3">
      <MiniCard icon={Plane} title="1. Extract"><BulletList items={['Collect domestic fares through Google Flights via SerpAPI.', 'Observe T+1, T+7, T+15, T+30 and T+60 departures.', 'Capture route, flight, total fare, price insights, source and timestamp.']} /></MiniCard>
      <MiniCard icon={SlidersHorizontal} title="2. Transform"><BulletList items={['Remove duplicates and quarantine incomplete records.', 'Preserve unavailable insight values as null and flag statistical outliers.', 'Normalize total fare and available Google price insights.', 'Standardise city pairs, dates, currency and booking windows.']} /></MiniCard>
      <MiniCard icon={Database} title="3. Load"><BulletList items={['Map validated records through the SQLAlchemy ORM.', 'Store the prototype dataset in SQLite.', 'Append time-stamped records to the historical airfare repository.']} /></MiniCard>
    </div>
    <Callout><strong>Business interpretation:</strong> ETL converts changing website displays into consistent statistical observations. Every stage preserves enough metadata for review and audit.</Callout>
    <div className="overflow-x-auto rounded-xl border border-[#E2E8F0]"><table className="w-full min-w-[660px] text-left text-xs"><thead className="bg-[#F8FAFC] text-[10px] uppercase tracking-wider text-[#64748B]"><tr><th className="px-4 py-3">Stage</th><th className="px-4 py-3">Input</th><th className="px-4 py-3">Control</th><th className="px-4 py-3">Output</th></tr></thead><tbody className="divide-y divide-[#EDF2F7] text-[#475569]"><tr><td className="px-4 py-3 font-bold">Extract</td><td className="px-4 py-3">Website result</td><td className="px-4 py-3">Source and timestamp captured</td><td className="px-4 py-3">Raw fare record</td></tr><tr><td className="px-4 py-3 font-bold">Transform</td><td className="px-4 py-3">Raw record</td><td className="px-4 py-3">Validation and standardisation</td><td className="px-4 py-3">Comparable observation</td></tr><tr><td className="px-4 py-3 font-bold">Load</td><td className="px-4 py-3">Validated observation</td><td className="px-4 py-3">Schema and uniqueness checks</td><td className="px-4 py-3">Historical repository row</td></tr></tbody></table></div>
  </div>;
}

function MethodologyContent() {
  return <div className="space-y-5">
    <div className="rounded-2xl border border-[#1769AA]/20 bg-[#0A2540] p-6 text-center text-white sm:p-8"><div className="text-[10px] font-extrabold uppercase tracking-[0.18em] text-sky-300">Weighted airfare price index</div><div className="mt-4 overflow-x-auto font-mono text-lg font-bold sm:text-2xl">APIX<sub>t</sub> = Σ (w<sub>i</sub> × P<sub>i,t</sub> / P<sub>i,base</sub>) × 100</div><p className="mt-4 text-xs leading-5 text-slate-300">Each route’s price change is multiplied by its passenger-share weight. The weighted results are added to produce the index.</p></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MiniCard icon={RouteIcon} title="wᵢ · Route weight">DGCA passenger share assigned to route i. Active weights are normalised to sum to 1 (or 100%).</MiniCard><MiniCard icon={Clock3} title="Pᵢ,base · Base fare">Comparable average fare for route i during the selected base period.</MiniCard><MiniCard icon={ReceiptIndianRupee} title="Pᵢ,t · Current fare">Comparable route fare for period t using the same fare definition and booking window.</MiniCard><MiniCard icon={Plane} title="Representative basket">Stable city pairs chosen to reflect important domestic passenger movements.</MiniCard></div>
    <div><h3 className="mb-3 font-heading text-base font-extrabold text-[#172033]">Worked example</h3><div className="overflow-x-auto rounded-xl border border-[#E2E8F0]"><table className="w-full min-w-[720px] text-left text-xs"><thead className="bg-[#F8FAFC] text-[10px] uppercase tracking-wider text-[#64748B]"><tr><th className="px-4 py-3">Route</th><th className="px-4 py-3">Weight</th><th className="px-4 py-3">Base fare</th><th className="px-4 py-3">Current fare</th><th className="px-4 py-3">Price relative</th><th className="px-4 py-3">Contribution</th></tr></thead><tbody className="divide-y divide-[#EDF2F7] text-[#475569]"><tr><td className="px-4 py-3 font-mono font-bold">DEL–BOM</td><td className="px-4 py-3">0.40</td><td className="px-4 py-3">₹5,000</td><td className="px-4 py-3">₹5,500</td><td className="px-4 py-3">110.0</td><td className="px-4 py-3">44.00</td></tr><tr><td className="px-4 py-3 font-mono font-bold">DEL–BLR</td><td className="px-4 py-3">0.35</td><td className="px-4 py-3">₹4,500</td><td className="px-4 py-3">₹4,725</td><td className="px-4 py-3">105.0</td><td className="px-4 py-3">36.75</td></tr><tr><td className="px-4 py-3 font-mono font-bold">BOM–BLR</td><td className="px-4 py-3">0.25</td><td className="px-4 py-3">₹4,000</td><td className="px-4 py-3">₹3,800</td><td className="px-4 py-3">95.0</td><td className="px-4 py-3">23.75</td></tr></tbody><tfoot className="bg-blue-50 font-extrabold text-[#172033]"><tr><td className="px-4 py-3" colSpan={5}>APIX for period t</td><td className="px-4 py-3 text-[#1769AA]">104.50</td></tr></tfoot></table></div></div>
    <Callout><strong>Interpretation:</strong> APIX 104.50 means the weighted fare basket is 4.5% above the base period. It does not mean the average ticket costs ₹104.50.</Callout>
    <div className="grid gap-4 md:grid-cols-3"><MiniCard icon={Activity} title="Daily APIX">Uses validated observations for an individual collection date and supports rapid monitoring.</MiniCard><MiniCard icon={BarChart3} title="Weekly APIX">Combines daily values using a documented weekly aggregation rule to reduce daily noise.</MiniCard><MiniCard icon={Gauge} title="Monthly APIX">Summarises the month for reporting and comparison with broader inflation indicators.</MiniCard></div>
  </div>;
}

function ScrapingContent() {
  const steps = [['1', 'Schedule', 'Python generates T+1, T+7, T+15, T+30 and T+60 searches for each domestic route.'], ['2', 'Request', 'The collector requests Google Flights results through the SerpAPI endpoint.'], ['3', 'Collect', 'Flight details, total fare and available price insights are normalized.'], ['4', 'Validate', 'The response is checked, retried within configured limits and passed to ETL.']];
  return <div className="space-y-5"><div className="grid gap-3 md:grid-cols-4">{steps.map(([number, title, text]) => <div key={number} className="rounded-2xl border border-[#E2E8F0] bg-white p-5"><div className="mb-3 flex h-7 w-7 items-center justify-center rounded-full bg-[#1769AA] text-xs font-extrabold text-white">{number}</div><h3 className="text-sm font-extrabold text-[#172033]">{title}</h3><p className="mt-1 text-xs leading-5 text-[#64748B]">{text}</p></div>)}</div>
    <div className="grid gap-4 lg:grid-cols-2"><MiniCard icon={RefreshCw} title="Limits and retries"><BulletList items={['Space API requests using the configured rate limit.', 'Retry temporary failures with bounded attempts.', 'Record failed routes without stopping the complete run.']} /></MiniCard><MiniCard icon={ShieldCheck} title="Controlled collection"><BulletList items={['Use the configured SerpAPI Google Flights endpoint only.', 'Keep raw responses and normalized run output for audit.', 'Track API quota exhaustion explicitly.', 'Keep a source and run log for governance review.']} /></MiniCard></div>
    <Callout tone="technical"><strong>SerpAPI Google Flights:</strong> the collector uses structured API responses instead of automating individual airline or OTA websites.</Callout>
    <div className="rounded-2xl border border-[#E2E8F0] bg-[#F8FAFC] p-5"><h3 className="font-heading text-sm font-extrabold text-[#172033]">Active source connector</h3><div className="mt-3 flex flex-wrap gap-2"><span className="rounded-lg border border-blue-100 bg-white px-3 py-2 text-xs font-bold text-[#1769AA]">Google Flights via SerpAPI</span></div><p className="mt-3 text-xs leading-5 text-[#64748B]">Individual airline and OTA collectors are not part of the current collection pipeline.</p></div>
  </div>;
}

function DashboardContent() {
  const widgets = [
    { icon: Activity, title: 'APIX Trend Chart', technical: 'The horizontal axis is time and the vertical axis is the index level. Hover to read the exact period value and movement.', business: 'A rising line signals airfare inflation against the base; compare persistent movement rather than one isolated point.' },
    { icon: RouteIcon, title: 'Route Heatmap', technical: 'Colours encode route fare movement or alert severity. Use date, route and booking-window controls to narrow the comparison.', business: 'Warm or high-severity colours identify inflation hotspots; always check the legend and observation coverage before concluding.' },
    { icon: BarChart3, title: 'Airline Comparison', technical: 'Compares average comparable fares and, where available, each airline’s contribution within the selected route and period.', business: 'Use it to understand whether market movement is broad or concentrated in particular carriers - not to rank service quality.' },
    { icon: Gauge, title: 'Lead-Time Elasticity', technical: 'Plots comparable fares across T+1, T+7, T+15, T+30 and T+45 windows for a route or market selection.', business: 'A steep rise near T+1 indicates a last-minute premium; a flatter curve suggests less sensitivity to booking time.' },
    { icon: Filter, title: 'Dashboard Filters', technical: 'Date, airline, route and booking-window filters update the applicable charts and summary cards to a common analytical slice.', business: 'Confirm active filters before comparing or exporting. Narrow filters may describe a segment, not the national market.' },
  ];
  return <div className="space-y-4">{widgets.map((widget) => <div key={widget.title} className="grid gap-4 rounded-2xl border border-[#E2E8F0] bg-white p-5 md:grid-cols-[220px_1fr_1fr]"><div className="flex items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-[#1769AA]"><widget.icon className="h-5 w-5" /></div><h3 className="font-heading text-sm font-extrabold text-[#172033]">{widget.title}</h3></div><div><div className="mb-1 text-[10px] font-extrabold uppercase tracking-wider text-[#94A3B8]">How it works</div><p className="text-xs leading-5 text-[#64748B]">{widget.technical}</p></div><div className="rounded-xl bg-[#F5F9FD] p-3"><div className="mb-1 text-[10px] font-extrabold uppercase tracking-wider text-[#1769AA]">Business interpretation</div><p className="text-xs leading-5 text-[#334155]">{widget.business}</p></div></div>)}<Callout tone="warning"><strong>Reading charts safely:</strong> check the selected date, route, airline, booking window, source coverage and data-quality status before using a visual in an official note.</Callout></div>;
}

const ROLE_GUIDES: Record<UserRole, { title: string; subtitle: string; icon: LucideIcon; tasks: readonly string[] }> = {
  NSO: { title: 'NSO Official', subtitle: 'CPI and official-statistics workflow', icon: Landmark, tasks: ['Monitor APIX alongside CPI transport indicators.', 'Review national and route-level APIX trends.', 'Download authorised reports with coverage notes.', 'Inspect representative route basket and passenger weights.'] },
  RBI: { title: 'RBI Analyst', subtitle: 'Inflation and risk-monitoring workflow', icon: Gauge, tasks: ['Track airfare inflation and transmission signals.', 'Compare route volatility and persistent movements.', 'Study lead-time behaviour and last-minute premiums.', 'Treat AI-generated observations as reviewable prompts, not official conclusions.'] },
  MOSPI_ADMIN: { title: 'MoSPI / DGCA Administrator', subtitle: 'Platform governance and data operations', icon: UserCog, tasks: ['Maintain route weights and effective basket settings.', 'Manage authorised government user access.', 'Monitor scraper schedules, failures and source health.', 'Review data-quality alerts and document resolution.'] },
};

function RolesContent({ role }: { role: UserRole | undefined }) {
  const availableRoles = Object.keys(ROLE_GUIDES) as UserRole[];
  const orderedRoles = role ? [role, ...availableRoles.filter((roleKey) => roleKey !== role)] : availableRoles;
  return <div className="space-y-5"><Callout><strong>Personalised entry:</strong> this section opened first for your signed-in role. All role guidance remains visible so cross-agency users can understand responsibilities.</Callout><div className="grid gap-4 lg:grid-cols-3">{orderedRoles.map((roleKey) => { const guide = ROLE_GUIDES[roleKey]; return <div key={roleKey} className={`rounded-2xl border p-5 ${roleKey === role ? 'border-[#1769AA] bg-blue-50/60 shadow-md shadow-blue-900/5' : 'border-[#E2E8F0] bg-white'}`}><div className="flex items-start justify-between gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-[#1769AA] shadow-sm"><guide.icon className="h-5 w-5" /></div>{roleKey === role && <span className="rounded-full bg-[#1769AA] px-2.5 py-1 text-[9px] font-extrabold uppercase tracking-wider text-white">Your role</span>}</div><h3 className="mt-4 font-heading text-base font-extrabold text-[#172033]">{guide.title}</h3><p className="mt-1 text-xs text-[#64748B]">{guide.subtitle}</p><div className="mt-4 text-xs leading-5 text-[#475569]"><BulletList items={guide.tasks} /></div></div>; })}</div><Callout tone="warning"><strong>Governance note:</strong> dashboard access follows role permissions. Analytical access does not by itself authorise changes to route weights, users or operational schedules.</Callout></div>;
}

function GlossaryContent() {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState<GlossaryCategory | 'All'>('All');
  const categories = Object.keys(CATEGORY_META) as GlossaryCategory[];
  const results = useMemo(() => { const needle = query.trim().toLowerCase(); return GLOSSARY.filter((entry) => (category === 'All' || entry.category === category) && (!needle || `${entry.term} ${entry.short ?? ''} ${entry.meaning} ${entry.importance}`.toLowerCase().includes(needle))); }, [category, query]);
  return <div className="space-y-4"><div className="flex flex-col gap-3 lg:flex-row"><label className="relative flex-1"><span className="sr-only">Search glossary terms</span><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-[#94A3B8]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search a term or abbreviation…" className="w-full rounded-xl border border-[#CBD5E1] bg-white py-3 pl-9 pr-9 text-xs outline-none focus:border-[#1769AA] focus:ring-3 focus:ring-blue-100" />{query && <button onClick={() => setQuery('')} aria-label="Clear glossary search" className="absolute right-2.5 top-1/2 -translate-y-1/2 text-[#64748B]"><X className="h-4 w-4" /></button>}</label><div className="flex gap-2 overflow-x-auto">{(['All', ...categories] as const).map((item) => <button key={item} onClick={() => setCategory(item)} className={`whitespace-nowrap rounded-xl border px-3 py-2 text-[10px] font-extrabold ${category === item ? 'border-[#1769AA] bg-[#1769AA] text-white' : 'border-[#E2E8F0] bg-white text-[#64748B]'}`}>{item}</button>)}</div></div><p className="text-[11px] font-semibold text-[#64748B]">Showing {results.length} of {GLOSSARY.length} terms</p>{results.length ? <div className="grid gap-4 xl:grid-cols-2">{results.map((entry) => { const meta = CATEGORY_META[entry.category]; const Icon = meta.icon; return <article key={entry.term} className="rounded-2xl border border-[#E2E8F0] bg-white p-5"><div className="flex items-start justify-between gap-3"><div><h3 className="font-heading text-sm font-extrabold text-[#172033]">{entry.term}</h3>{entry.short && <div className="mt-1 font-mono text-[11px] font-extrabold text-[#1769AA]">{entry.short}</div>}</div><span title={entry.category} className={`rounded-lg p-2 ring-1 ring-inset ${meta.tone}`}><Icon className="h-3.5 w-3.5" /></span></div><div className="mt-4 grid gap-3 border-t border-[#EDF2F7] pt-4 sm:grid-cols-2"><div><div className="text-[9px] font-extrabold uppercase tracking-wider text-[#94A3B8]">Meaning</div><p className="mt-1 text-xs leading-5 text-[#64748B]">{entry.meaning}</p></div><div className="rounded-xl bg-[#F5F9FD] p-3"><div className="text-[9px] font-extrabold uppercase tracking-wider text-[#1769AA]">Why it matters</div><p className="mt-1 text-xs leading-5 text-[#334155]">{entry.importance}</p></div></div></article>; })}</div> : <div className="rounded-xl border border-dashed border-[#CBD5E1] bg-white py-10 text-center text-xs text-[#64748B]">No glossary terms match the current filters.</div>}</div>;
}

function FaqContent() {
  return <div className="overflow-hidden rounded-2xl border border-[#E2E8F0] bg-white"><div className="grid grid-cols-[52px_1fr] border-b border-[#E2E8F0] bg-[#F8FAFC] px-4 py-3 text-[10px] font-extrabold uppercase tracking-wider text-[#64748B]"><span>No.</span><span>Question and answer</span></div><div className="divide-y divide-[#EDF2F7]">{FAQS.map(([question, answer], index) => <div key={question} className="grid grid-cols-[52px_1fr] px-4 py-4"><span className="font-mono text-xs font-bold text-[#94A3B8]">{String(index + 1).padStart(2, '0')}</span><div><h3 className="text-xs font-extrabold text-[#172033]">{question}</h3><p className="mt-1.5 text-xs leading-5 text-[#64748B]">{answer}</p></div></div>)}</div></div>;
}

function SectionContent({ id, role }: { id: SectionId; role: UserRole | undefined }) {
  if (id === 'etl') return <EtlContent />;
  if (id === 'methodology') return <MethodologyContent />;
  if (id === 'scraping') return <ScrapingContent />;
  if (id === 'dashboard') return <DashboardContent />;
  if (id === 'roles') return <RolesContent role={role} />;
  if (id === 'glossary') return <GlossaryContent />;
  return <FaqContent />;
}

export function UserGuidePage() {
  const { user } = useAuth();
  const [query, setQuery] = useState('');
  const [openSections, setOpenSections] = useState<Set<SectionId>>(() => new Set(['roles']));
  const normalizedQuery = query.trim().toLowerCase();
  const visibleSections = useMemo(() => GUIDE_SECTIONS.filter((section) => !normalizedQuery || `${section.title} ${section.description} ${section.searchText}`.toLowerCase().includes(normalizedQuery)), [normalizedQuery]);
  const toggleOpen = (id: SectionId) => setOpenSections((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const allVisibleOpen = visibleSections.length > 0 && visibleSections.every((section) => openSections.has(section.id));

  return <div className="pb-16">
    <nav aria-label="Breadcrumb" className="mb-5 flex items-center gap-2 text-xs font-semibold text-[#64748B]"><BookOpen className="h-3.5 w-3.5" /> Help Center <span className="text-[#CBD5E1]">/</span><span className="text-[#1769AA]">Government User Guide</span></nav>
    <header className="overflow-hidden rounded-3xl bg-[#0A2540] px-5 py-8 text-white shadow-xl shadow-slate-900/10 sm:px-8 lg:px-10"><div className="mb-3 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/10 px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-[0.16em] text-blue-100"><Building2 className="h-3.5 w-3.5" /> Official platform documentation</div><h1 className="font-heading text-3xl font-extrabold tracking-tight sm:text-4xl">VAYUSETU User Guide</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-slate-300">Technical workflow and business guidance for airfare inflation monitoring, written for government officials and first-time users.</p></header>
    <main className="mt-6 min-w-0"><section aria-label="Search guide" className="rounded-2xl border border-[#E2E8F0] bg-white p-4 shadow-sm"><div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Search the User Guide</span><Search className="absolute left-3.5 top-1/2 h-4 w-4 -translate-y-1/2 text-[#94A3B8]" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search workflows, charts, roles, FAQs or terms…" className="w-full rounded-xl border border-[#CBD5E1] bg-[#F8FAFC] py-3 pl-10 pr-10 text-xs outline-none focus:border-[#1769AA] focus:bg-white focus:ring-3 focus:ring-blue-100" />{query && <button onClick={() => setQuery('')} aria-label="Clear guide search" className="absolute right-3 top-1/2 -translate-y-1/2 text-[#64748B]"><X className="h-4 w-4" /></button>}</label><button onClick={() => setOpenSections(allVisibleOpen ? new Set() : new Set(GUIDE_SECTIONS.map((section) => section.id)))} className="rounded-xl border border-[#CBD5E1] px-4 py-3 text-xs font-extrabold text-[#475569] hover:border-[#1769AA] hover:text-[#1769AA]">{allVisibleOpen ? 'Collapse All' : 'Expand All'}</button></div>{query && <div aria-live="polite" className="mt-2 text-[11px] text-[#64748B]">{visibleSections.length} section{visibleSections.length === 1 ? '' : 's'} match “{query}”</div>}</section>
      <div className="mt-5 space-y-4">{visibleSections.map((section) => { const Icon = section.icon; const expanded = openSections.has(section.id); return <section key={section.id} id={`guide-${section.id}`} className={`scroll-mt-24 overflow-hidden rounded-2xl border bg-white transition ${expanded ? 'border-[#CBD5E1] shadow-md shadow-slate-900/5' : 'border-[#E2E8F0]'}`}><button onClick={() => toggleOpen(section.id)} aria-expanded={expanded} aria-controls={`guide-panel-${section.id}`} className="flex w-full items-center gap-4 p-5 text-left sm:p-6"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-blue-50 text-[#1769AA]"><Icon className="h-5 w-5" /></span><span className="min-w-0 flex-1"><span className="block text-[9px] font-extrabold uppercase tracking-[0.16em] text-[#1769AA]">Section {section.letter}</span><span className="mt-0.5 block font-heading text-base font-extrabold text-[#172033] sm:text-lg">{section.title}</span><span className="mt-1 hidden text-xs text-[#64748B] sm:block">{section.description}</span></span><ChevronDown className={`h-5 w-5 shrink-0 text-[#94A3B8] transition-transform ${expanded ? 'rotate-180' : ''}`} /></button>{expanded && <div id={`guide-panel-${section.id}`} className="border-t border-[#EDF2F7] bg-[#FCFDFE] p-5 sm:p-6"><SectionContent id={section.id} role={user?.role} /></div>}</section>; })}{visibleSections.length === 0 && <div className="rounded-2xl border border-dashed border-[#CBD5E1] bg-white py-14 text-center"><Search className="mx-auto h-8 w-8 text-[#94A3B8]" /><h2 className="mt-3 font-heading text-base font-extrabold text-[#172033]">No guide sections found</h2><p className="mt-1 text-xs text-[#64748B]">Try a broader search such as “fare”, “route” or “dashboard”.</p><button onClick={() => setQuery('')} className="mt-4 rounded-xl bg-[#1769AA] px-4 py-2.5 text-xs font-extrabold text-white">Clear search</button></div>}</div>
    </main>
  </div>;
}
